name: rmw
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.4
  isar_generator: ^0.4.0
  lints: ^1.0.0

dependencies: 
  isar: ^0.4.0
